fix: compilation error under GCC 14.3.0
This was caused after https://github.com/supabase/supautils/pull/166.

src/supautils.c: In function ‘supautils_hook’:
src/supautils.c:471:26: error: variable ‘stmt’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
  471 |     CreateExtensionStmt *stmt = (CreateExtensionStmt *)utility_stmt;
      |                          ^~~~

The fix is simply adding a `volatile *stmt`, but that does signal something else might be wrong here.