feat: add hint when GRANT privilege is missing
Whenever we hit an ERRCODE_INSUFFICIENT_PRIVILEGE, we give a hint for
the precise privilege missing for the current role.

Simple SELECT:

```sql
select from hint_target;
ERROR:  permission denied for table hint_target
HINT:  Grant the required privileges to the current role with: GRANT SELECT ON public.hint_target TO hint_role;
```

If multiple privileges are missing on an upsert:

```sql
insert into hint_target(id)
values (1)
on conflict (id) do update set id = excluded.id;
ERROR:  permission denied for table hint_target
HINT:  Grant the required privileges to the current role with: GRANT SELECT, INSERT, UPDATE ON public.hint_target TO hint_role;
```

These hints are critical now that we're going to be secure by default.

NOTES:

- This is done by adding an ExecutorStart_hook which only purpose is to
  catch the ERRCODE_INSUFFICIENT_PRIVILEGE error and override the empty
  privilege.