feat: add hint when GRANT privilege is missing (#178)
Whenever we hit an ERRCODE_INSUFFICIENT_PRIVILEGE, we give a hint for
the precise privilege missing for the current role.

Simple SELECT:

```sql
select from hint_target;
ERROR:  permission denied for table hint_target
HINT:  Grant the required privileges to the current role with: GRANT SELECT ON public.hint_target TO hint_role;
```

If multiple privileges are missing on an upsert:

```sql
insert into hint_target(id)
values (1)
on conflict (id) do update set id = excluded.id;
ERROR:  permission denied for table hint_target
HINT:  Grant the required privileges to the current role with: GRANT SELECT, INSERT, UPDATE ON public.hint_target TO hint_role;
```

NOTES:

- This is done by adding an ExecutorStart_hook which only purpose is to
  catch the ERRCODE_INSUFFICIENT_PRIVILEGE error and override the empty
  privilege.
- Also adds a loadtest for a simple select to ensure the perf loss is not great (the impact is around 1-2%, mostly due to the `is_hint_role` check)
- Hints for views under pg 18 are not working and left as TODO, hints for views on all the previous versions work normally