feat: pin an extension version
Solves https://github.com/supabase/supautils/pull/187.

By doing:

```sql
supautils.extensions_parameter_overrides = '{"hstore":{"version":"1.7"}}';
```

We can pin an extension to a version, even if the user creates it with a
different one:

```sql
create extension hstore version '1.4';

select extversion from pg_extension where extname = 'hstore';
 extversion
------------
 1.7
(1 row)
```

ALTERing a extension doesn't work already but this is unrelated to this
feature:

```sql
alter extension hstore update to '1.8';
ERROR:  must be owner of extension hstore

select extversion from pg_extension where extname = 'hstore';
 extversion
------------
 1.7
(1 row)
```

The ideal behavior for this is allowing the ALTER to succeed but forcing
the version we specified. To solve this both https://github.com/supabase/supautils/issues/118
and https://github.com/supabase/supautils/issues/203 have to be cleared
first.

However as it is, this is sufficient for solving https://github.com/supabase/supautils/pull/187.