fix: late validation on supautils.constrained_extensions
supautils.constrained_extensions was using the `assign_hook`
to do validation but it's a bad place because it runs too late.

So when you do:

```sql
-- this is invalid but it's allowed first time
alter system  set supautils.constrained_extensions to '{"plrust": []}';
select pg_reload_conf();
 pg_reload_conf
----------------
 t
(1 row)
alter system  set supautils.constrained_extensions to '{"plrust": []}';
ERROR:  supautils.constrained_extensions: unexpected array
```

With this change:

```
alter system  set supautils.constrained_extensions to '{"x": []}';
ERROR:  supautils.constrained_extensions: unexpected array
```

The fix was using a check_hook in addition to the assign_hook.

This also improves the tests checking this behavior.