Merge commit from fork
* fix: CVE-2026-14669

Problem
-------

Check https://www.postgresql.org/support/security/CVE-2026-14669/.

The root cause of the CVE is that the `timezone` GUC accepts long values
that overflow `to_char`.

The [patch in pg](https://github.com/postgres/postgres/commit/3d724bf4fde67a2931733a5143b7d6c12b23990c) solves it like this:

```
postgres=# set timezone = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx0';
SET
postgres=# select to_char(timestamptz '2000-01-15 12:00:00+00', 'TZ');
2026-08-24 19:27:49.310 -05 [115381] ERROR:  time zone format value too long
2026-08-24 19:27:49.310 -05 [115381] STATEMENT:  select to_char(timestamptz '2000-01-15 12:00:00+00', 'TZ');
ERROR:  time zone format value too long
```

Newer versions don't give the error since they solve it by using
StringInfo ([ref](https://github.com/postgres/postgres/commit/03d2554638c)) which uses an expansible buffer instead.

Solution
--------

Instead of failing at `to_char` time, we do it when setting the
`timezone` GUC via check hook:

```sql
set timezone = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0';
ERROR:  timezone values cannot be longer than 24 bytes
```

This way `to_char` doesn't overflow since the long timezone doesn't
reach it.

Notes
-----

- Limitation: some valid timezones are rejected, like `posix/America/Argentina/ComodRivadavia`. In theory we could be more sophisticated with our parsing and only reject POSIX values,
  but IMO this is dangerous business, so the fix is kept as simple as possible.
- For suabase prod, the list of all rejected timezones are these: `select length(name), * from pg_timezone_names where length(name) > 24;`:

| length | name                                   | abbrev | utc_offset | is_dst |
| ------ | -------------------------------------- | ------ | ---------- | ------ |
| 25     | Antarctica/DumontDUrville              | +10    | 10:00:00   | false  |
| 26     | posix/Africa/Dar_es_Salaam             | EAT    | 03:00:00   | false  |
| 25     | posix/Africa/Johannesburg              | SAST   | 02:00:00   | false  |
| 25     | posix/Pacific/Guadalcanal              | +11    | 11:00:00   | false  |
| 26     | posix/Pacific/Bougainville             | +11    | 11:00:00   | false  |
| 26     | posix/Pacific/Port_Moresby             | +10    | 10:00:00   | false  |
| 26     | posix/Antarctica/Macquarie             | AEST   | 10:00:00   | false  |
| 31     | posix/Antarctica/DumontDUrville        | +10    | 10:00:00   | false  |
| 27     | posix/Antarctica/South_Pole            | NZST   | 12:00:00   | false  |
| 25     | posix/Indian/Antananarivo              | EAT    | 03:00:00   | false  |
| 25     | posix/Arctic/Longyearbyen              | CEST   | 02:00:00   | true   |
| 28     | posix/Atlantic/South_Georgia           | -02    | -02:00:00  | false  |
| 25     | posix/Atlantic/Cape_Verde              | -01    | -01:00:00  | false  |
| 25     | posix/Canada/Saskatchewan              | CST    | -06:00:00  | false  |
| 25     | posix/Canada/Newfoundland              | NDT    | -02:30:00  | true   |
| 27     | posix/America/Ciudad_Juarez            | MDT    | -06:00:00  | true   |
| 26     | posix/America/Indianapolis             | EDT    | -04:00:00  | true   |
| 25     | posix/America/Pangnirtung              | EDT    | -04:00:00  | true   |
| 27     | posix/America/Cambridge_Bay            | MDT    | -06:00:00  | true   |
| 28     | posix/America/Bahia_Banderas           | CST    | -06:00:00  | false  |
| 34     | posix/America/Indiana/Indianapolis     | EDT    | -04:00:00  | true   |
| 31     | posix/America/Indiana/Tell_City        | CDT    | -05:00:00  | true   |
| 29     | posix/America/Indiana/Winamac          | EDT    | -04:00:00  | true   |
| 29     | posix/America/Indiana/Marengo          | EDT    | -04:00:00  | true   |
| 31     | posix/America/Indiana/Vincennes        | EDT    | -04:00:00  | true   |
| 27     | posix/America/Indiana/Vevay            | EDT    | -04:00:00  | true   |
| 32     | posix/America/Indiana/Petersburg       | EDT    | -04:00:00  | true   |
| 26     | posix/America/Indiana/Knox             | CDT    | -05:00:00  | true   |
| 26     | posix/America/Punta_Arenas             | -03    | -03:00:00  | false  |
| 26     | posix/America/Santa_Isabel             | PDT    | -07:00:00  | true   |
| 25     | posix/America/El_Salvador              | CST    | -06:00:00  | false  |
| 26     | posix/America/Buenos_Aires             | -03    | -03:00:00  | false  |
| 25     | posix/America/Tegucigalpa              | CST    | -06:00:00  | false  |
| 26     | posix/America/Rankin_Inlet             | CDT    | -05:00:00  | true   |
| 36     | posix/America/North_Dakota/New_Salem   | CDT    | -05:00:00  | true   |
| 33     | posix/America/North_Dakota/Beulah      | CDT    | -05:00:00  | true   |
| 33     | posix/America/North_Dakota/Center      | CDT    | -05:00:00  | true   |
| 33     | posix/America/Kentucky/Louisville      | EDT    | -04:00:00  | true   |
| 33     | posix/America/Kentucky/Monticello      | EDT    | -04:00:00  | true   |
| 25     | posix/America/Rainy_River              | CDT    | -05:00:00  | true   |
| 25     | posix/America/Porto_Velho              | -04    | -04:00:00  | false  |
| 27     | posix/America/Coral_Harbour            | EST    | -05:00:00  | false  |
| 27     | posix/America/St_Barthelemy            | AST    | -04:00:00  | false  |
| 26     | posix/America/Dawson_Creek             | MST    | -07:00:00  | false  |
| 26     | posix/America/Blanc-Sablon             | AST    | -04:00:00  | false  |
| 25     | posix/America/Yellowknife              | MDT    | -06:00:00  | true   |
| 25     | posix/America/Mexico_City              | CST    | -06:00:00  | false  |
| 28     | posix/America/Port-au-Prince           | EDT    | -04:00:00  | true   |
| 27     | posix/America/Port_of_Spain            | AST    | -04:00:00  | false  |
| 27     | posix/America/Lower_Princes            | AST    | -04:00:00  | false  |
| 38     | posix/America/Argentina/ComodRivadavia | -03    | -03:00:00  | false  |
| 31     | posix/America/Argentina/Cordoba        | -03    | -03:00:00  | false  |
| 36     | posix/America/Argentina/Rio_Gallegos   | -03    | -03:00:00  | false  |
| 36     | posix/America/Argentina/Buenos_Aires   | -03    | -03:00:00  | false  |
| 31     | posix/America/Argentina/Ushuaia        | -03    | -03:00:00  | false  |
| 32     | posix/America/Argentina/San_Luis       | -03    | -03:00:00  | false  |
| 33     | posix/America/Argentina/Catamarca      | -03    | -03:00:00  | false  |
| 31     | posix/America/Argentina/Tucuman        | -03    | -03:00:00  | false  |
| 29     | posix/America/Argentina/Salta          | -03    | -03:00:00  | false  |
| 29     | posix/America/Argentina/Jujuy          | -03    | -03:00:00  | false  |
| 32     | posix/America/Argentina/San_Juan       | -03    | -03:00:00  | false  |
| 31     | posix/America/Argentina/Mendoza        | -03    | -03:00:00  | false  |
| 32     | posix/America/Argentina/La_Rioja       | -03    | -03:00:00  | false  |
| 26     | posix/America/Danmarkshavn             | GMT    | 00:00:00   | false  |
| 27     | posix/America/Swift_Current            | CST    | -06:00:00  | false  |
| 25     | posix/America/Fort_Nelson              | MST    | -07:00:00  | false  |
| 25     | posix/America/Thunder_Bay              | EDT    | -04:00:00  | true   |
| 25     | posix/America/Los_Angeles              | PDT    | -07:00:00  | true   |
| 27     | posix/America/Santo_Domingo            | AST    | -04:00:00  | false  |
| 26     | posix/America/Campo_Grande             | -04    | -04:00:00  | false  |
| 25     | posix/America/Puerto_Rico              | AST    | -04:00:00  | false  |
| 26     | posix/America/Scoresbysund             | -01    | -01:00:00  | true   |
| 25     | posix/Australia/Melbourne              | AEST   | 10:00:00   | false  |
| 26     | posix/Australia/Yancowinna             | ACST   | 09:30:00   | false  |
| 26     | posix/Australia/Queensland             | AEST   | 10:00:00   | false  |
| 27     | posix/Australia/Broken_Hill            | ACST   | 09:30:00   | false  |
| 25     | posix/Australia/Lord_Howe              | +1030  | 10:30:00   | false  |
| 28     | America/Indiana/Indianapolis           | EDT    | -04:00:00  | true   |
| 25     | America/Indiana/Tell_City              | CDT    | -05:00:00  | true   |
| 25     | America/Indiana/Vincennes              | EDT    | -04:00:00  | true   |
| 26     | America/Indiana/Petersburg             | EDT    | -04:00:00  | true   |
| 30     | America/North_Dakota/New_Salem         | CDT    | -05:00:00  | true   |
| 27     | America/North_Dakota/Beulah            | CDT    | -05:00:00  | true   |
| 27     | America/North_Dakota/Center            | CDT    | -05:00:00  | true   |
| 27     | America/Kentucky/Louisville            | EDT    | -04:00:00  | true   |
| 27     | America/Kentucky/Monticello            | EDT    | -04:00:00  | true   |
| 32     | America/Argentina/ComodRivadavia       | -03    | -03:00:00  | false  |
| 25     | America/Argentina/Cordoba              | -03    | -03:00:00  | false  |
| 30     | America/Argentina/Rio_Gallegos         | -03    | -03:00:00  | false  |
| 30     | America/Argentina/Buenos_Aires         | -03    | -03:00:00  | false  |
| 25     | America/Argentina/Ushuaia              | -03    | -03:00:00  | false  |
| 26     | America/Argentina/San_Luis             | -03    | -03:00:00  | false  |
| 27     | America/Argentina/Catamarca            | -03    | -03:00:00  | false  |
| 25     | America/Argentina/Tucuman              | -03    | -03:00:00  | false  |
| 26     | America/Argentina/San_Juan             | -03    | -03:00:00  | false  |
| 25     | America/Argentina/Mendoza              | -03    | -03:00:00  | false  |
| 26     | America/Argentina/La_Rioja             | -03    | -03:00:00  | false  |

- AFAICT all the above have an alternative timezone.

- We can be nicer and give a hint, telling users they have to
  search on `pg_timezone_names` for equivalent timezones or tell them to
  upgrade.

* fix: do not allow timezones with long abbreviations

* chore: use strnlen instead of strlen

* fix: look for all abbreviations

* test: startup packet validation

and remove comment about manual tests

* refactor: vendor Postgres code into separate files

* fix: startup tests were not using postgres version

* fix: harden against prev check hook not running

---------

Co-authored-by: steve-chavez <stevechavezast@gmail.com>